FrontMen/fm-hours

- pages/users.vue
- services/users-service.ts
- store/reports/mutations.ts
- store/timesheets/actions.ts
- store/users/actions.ts
- types/user.d.ts
- Adds `active` field to user objects
- Hides inactive users in `timesheets` and `reports` pages.
resolves #20
> Feat: inactive users

- components/records/weekly-timesheet-footer.vue
- pages/records.vue
Allows the user to `unsubmit` the timesheet so they can edit it again.
resolves #17
> Feat: unsubmit timesheet

- pages/records.vue
As we want to avoid writing too much documents, we're not auto-saving on input. This could be annoying when switching weeks without saving, so we show a confirmation dialog before switching week when the user has unsaved changes.
resolves #21
> feat: ask confirmation when switching week with unsaved changes

- components/records/weekly-timesheet-totals-row.vue
- helpers/timesheet.ts
Makes the `leave` and `absence` projects editable again, like other projects. I kept the logic in place for when the API is implemented.
resolves #22 
---
Related to #9
> feat: disabled workscheme logic

- components/records/weekly-timesheet-footer.vue
- helpers/timesheet.ts
- pages/records.vue
When copying a previous week which was already `submitted` or `approved` it would use this status for the new week as well. It's setting the status to `NEW` for the newly copied week.
> fix: dont copy weekly status from previous week

- .github/PULL_REQUEST_TEMPLATE.md
- composables/useMonthlyProjectsReport.ts
- Resolves #59 
- Add GitHub PR template
N/A
- Add debtor column to the Projects timesheet on reports
- Go to the Projects tab on /reports and check if we have a Debtor column
> feat: add debtor to reports

- components/records/weekly-timesheet-footer.vue
- components/timesheets/weekly-timesheet-admin-footer.vue
Resolves #57 
N/A
N/A
- Text of the save button on the timesheets page
- It is disabled when we don't have changes to save
- Check if the button now shows "Update" as its text
- Check if the Update button is disabled when we don't have changes to save
N/A
> Refactor(timesheets): rename actions

- pages/employees/_employee_id.vue
- pages/employees/index.vue
- store/employees/actions.ts
Resolves #54 
- `employees/updateEmployee` action
- `employees/toggleActive` action
- `employees/toggleTravelAllowance` action
- Employee controls are now on the employee detail page
- Navigate to the employee detail page (Click on the "Manage employee" button on the employee page )
- Try to change the employee data toggling the switches
- The changes should only be saved after clicking the "Save" button.
- Employees page
- Employee detail page
> feat(employees): add actions to detail page

- components/records/weekly-timesheet-row.vue
- components/timesheets/timesheet-employee-row.vue
- helpers/employee.ts
- helpers/timesheet.ts
- pages/employees/_employee_id.vue
- pages/records.vue
- services/employees-service.ts
- store/reports/actions.ts
- store/reports/mutations.ts
- store/timesheets/actions.ts
- types/employee.d.ts
Resolves #49 
- Now on the timesheet page the employees are sorted by status
- End date field on the employee schema
- Active field on the employee schema
- We check if the employee is active or not per date, using the endDate prop
- Input value is selected when focused on editable timesheets
- Check if inactive employees are showing on reports of past dates when they were still active
- Check if employees are sorted by status (PENDING, DENIED, and NEW) on the timesheets page
- The employee should still be able to add hours to dates when he was still active
N/A
> Feat: employee end date

- components/records/weekly-timesheet-row.vue
N/A
N/A
N/A
- Return the correct boolean value when the employee has an end date
- Check if you can correctly edit the record inputs before the employee end date
N/A
> fix: adjust isReadonlyList logic

- components/records/navigation-buttons.vue
- composables/useTimesheet.ts
- helpers/dates.ts
- helpers/record-status.ts
- helpers/timesheet.ts
- pages/holidays.vue
- plugins/filters.ts
- services/holidays-service.ts
- store/records/actions.ts
- store/reports/actions.ts
- store/timesheets/actions.ts
Resolves #68 and #69 
- New date helper methods to handle timezones
- Helper functions on dates and record-status files that weren’t being used anymore.
- Now the application carefully converts dates to a standard GMT timezone on runtime to correctly compare dates without any conflict due to timezone differences.
- Go through all functionalities and check if there is inconsistency on dates or on data fetched by dates.
N/A
> Feat: add timezone support

- components/timesheets/weekly-timesheet-admin-footer.vue
- composables/useTimesheet.ts
- pages/records.vue
- types/timesheets.d.ts
Solves #25 
- Reason of denial field on timesheets
- Modal to add the reason of denial when denying a timesheet
- Show reason of denial message when seeing the denied record
- The DENY emmit event
N/A
- Try to deny a timesheet
- A modal should show, asking you to add the reason for denial
- See if the message is shown when viewing the given timesheet
- Submit the timesheet again and check if the message disappears
> Feat: add reason of denial message

- pages/employees/index.vue
Solves #81 
N/A
N/A
- Change link to employee page to use absolute path
- Click on a link to an employee page and check if it works
N/A
> fix(employees): change to absolute path

- components/records/weekly-timesheet-row.vue
- components/records/weekly-timesheet-totals-row.vue
- helpers/timesheet.ts
Solves #95 
- The Application already has support to float numbers, but due to localization, devices using Chrome with a locale that uses comma as float point separator won't be able to use dot. This PR adds a workaround to use the dot as the standardized separator.
- More details on this problem here: https://medium.com/takeaway-tech/solving-cross-browsers-localization-on-numeric-inputs-3f7aec57aaeb
N/A
N/A
- Records inputs now are of type text
- Truncated values to one decimal place
- Shows NaN when invalid input is temporarily placed
- Changes to a securely converted value on input blur
- Try to add float numbers as timerecords
N/A
> feat(records): use dot as float point separator

- composables/useTimesheet.ts
Resolves #94 
N/A
N/A
- Clear ids arrays for projects and travel projects when copying the previous week records
- Correctly get the previous week's date even on different time zones.
- Create a timesheet and save it
- Go to the next week and copy the previous records
- Deleting or updating the new records shouldn’t affect the previous records
N/A
> fix(records): delete ids on copy timesheet

- composables/useTimesheet.ts
N/A
- unsavedWeeklyTimesheet ref on the records page
N/A
- Now we save the state of the input values to persist after a row deletion (that causes a rerender due to Vuex update)
- Add multiple rows on a timesheet
- Delete a row
- Check if the other rows are unchanged
N/A
> fix(records): add unsaved weekly timesheet ref

- composables/useTimesheet.ts
Solves #96 
N/A
N/A
- Remove the unnecessary timezone conversion and just used the local date instead. Now the records page can fetch the correct timesheet.
- Go to the timesheets page
- Click on one of the tiles buttons
- Check if it navigates to the right week
N/A
> fix(timesheets): remove timezone conversion of start date

- components/records/weekly-timesheet-row.vue
- components/records/weekly-timesheet.vue
- composables/useTimesheet.ts
- helpers/dates.ts
- store/records/actions.ts
Solves #100 
- Request confirmation before saving hours of weekends or holidays
- Add a column mark for holidays
N/A
- Pass holidays to the `buildWeek` function calls
- Check if is a holiday comparing strings (ISO formatted) and not dates
- Darker background for holidays and weekends 
- Check if holidays and weekends get the dark gray background 
- Add hours to a holiday or weekend and try to save
- A confirmation pop-up should appear asking if you want to save it anyway 
N/A
> Fix: holidays not working

- components/records/navigation-buttons.vue
- pages/records.vue
Resolves #98 
- Back button on the admin view of the records page to go to the timesheets page
N/A
N/A
- Go to a timesheet approval page
- Click on the "< Timesheets" button
- Check if it goes back to the timesheets page
> feat(timesheets): add back to timesheets button

- store/employee/actions.ts
N/A
N/A
N/A
- Always pass email to `isAdmin` function
- Check if we properly return if an employee is an admin
N/A
> fix(employee): always pass email to get admin

- components/app/admin-sidebar.vue
Sidebar links created dynamically from a link array. 
Sidebar links using history.push instead of href to prevent reload on nav. 
admin-sidebar.vue - link list dynamically created from array. 
As an admin, open the sidebar and navigate. Note that navigation does not trigger page refresh.
> Use SPA link for sidebar items

- services/auth-service.ts
- store/employee/actions.ts
N/A
- remove auth cookie on logout 
N/A
- Pass full URL of auth API call
- Check if possible to login on `prod` environment 
N/A
> fix(auth): add full url and clear cookie

- store/employee/actions.ts
N/A
N/A
N/A
- Use a new instance of `authService` instead of the global one. The previous state was causing an error because the `logout` method was being invoked inside the `onAuthStateChanged` method that is triggered before the plugins injection
- Get logged out by an expired ppid (or a mocked invalid ppid)
- Check if the app logs out without any unexpected exception
N/A
> fix(auth): use new instace of authService on logout

- services/time-records-service.ts
- store/reports/actions.ts
June has 22 working days; i.e. 176 hours for fulltime ppl.
Ppl (for example Anthony or Ye Jun) have submitted their timesheets and filled in every day; a total of 176 hours for June.
On the report page only 168 hours are showing up in the totals - it seems that there's a day missing.
Removed getDayOnGMT from the variable startDate and endDate. Was giving incorrect date in local time (e.g 29th June instead of 30th June)
Initially the fire store query looked for time records between the first day of the month and the last day of the month. Problem is that the last day of the month wouldn't taken into account the whole day itself (e.g. time 00:00 on 30 June). So the query wouldn't get the record for the 30th. Now the query looks for records between 1 June 00:00 and 1 July 00:00.
Please test …
> fix: get correct time records for a given month

- pages/employees/index.vue
Fixes filtering on employee view - empty users can cause the page to break.
employees/index.vue 
Failsafe checks if values exist to perform to use a query against. 
In dev env, where we have such a faulty employee, use filters from employees page.
> Fix - empty employee leads to breaking filters on employees page

- pages/records.vue
Banner on /record prompts employee to navigate to Bridge to request or manage leave/absence. 
https://github.com/FrontMen/fm-hours/issues/89
Banner added on records.vue
Navigate to app as employee, or navigate to /records as admin. 
Note  banner with link to bridge. 
Link opens a new tab towards bridge absences
If logged out of bridge, bridge login flow and redirect to absences handled by bridge.
> Add banner to send employee to intracto bridge app to manage leave

- composables/useTimesheet.ts
- store/timesheets/actions.ts
- store/timesheets/mutations.ts
- store/timesheets/state.ts
- types/timesheets.d.ts
Make it possible for previous week's comment to be carried over when copying the week's timesheet
https://github.com/FrontMen/fm-hours/issues/130
Action that retrives a single timesheet based on employee and interval, and stores it to previousTimeSheet in store. 
The more generic action would override the currently created timesheet with the old values, including the status. Rewriting it to match the new usecase risks breaking functionality, so I went with extending to a more specific scenario. 
useTimesheets.ts #copyPreviousWeek now dispatches an event to retrieve previous timesheet. The #message is updated previousTImesheet alongside timesheet updates. 
Fill in a week including a message.
Copy the week's values into a new timesheet
Note the comment persists into the new timesheet too. …
> Copy comment from previous week's timesheet

- components/reports/reports-table.vue
https://github.com/FrontMen/fm-hours/issues/153
Added necessary .csv extension to the files
Go to reports page and export it in WINDOWS and MAC
https://user-images.githubusercontent.com/7356299/125065495-2f761380-e0b2-11eb-804a-c84fd61cc094.mov
> fix: add csv file extension to end of file

- helpers/helpers.ts
- pages/customers/index.vue
- pages/employees/index.vue
- pages/timesheets/index.vue
- store/filters/actions.ts
- store/filters/getters.ts
- store/filters/mutations.ts
- store/filters/state.ts
- types/filters.d.ts
Sorting order applicable to customers list.
Store filters from /customers, /employees and /timesheets
https://github.com/FrontMen/fm-hours/issues/91
customers/index.vue Added a select dropdown to manage sort order. Added sorting to computed filteredCustomers
helpers.ts has a generic sortByProp function
As an admin, navigate to /customers.
Change sort criteria, note the change in order.
Filter by keyword, note sort order is kept
Selecting "none" will return to unsorted list
Go to /customers, /employees or /timesheets and apply some filter and sort proprieties
Go to a subpage
Return - see the same filters persisting
Updated images found in the comments
> Add sorting to customer list

- components/records/empty-timesheet.vue
https://github.com/FrontMen/fm-hours/issues/82
Removed `if check` for admins to be able to add new timesheet's if it is empty
If logged in as an admin, empty timesheet days for an employee now should show the same page as home screen. Home screen is where employee tries to add a timesheet of its own.
https://user-images.githubusercontent.com/7356299/125615006-f8c73514-903f-4afb-ba6d-8b66f4fa4601.mov
> feat: enable admins to add new projects / timesheets for any user

- pages/employees/_employee_id.vue
- pages/employees/index.vue
- services/employees-service.ts
- store/employees/actions.ts
- store/employees/getters.ts
- store/employees/mutations.ts
- store/employees/state.ts
- types/employee.d.ts
- types/employees.d.ts
Added dropdown to set team to an employee on employee manage view
https://github.com/FrontMen/fm-hours/issues/60
Added dropdown to set team to an employee on employee manage view
1. Go to /employees
2. Go to manage on an employee
3. Change value in team dropdown and save
4. Refresh to see value retrieved or check inside firestore
firestore dev example
rule in firestore
> Add teams dropdown for employee

- components/timesheets/weekly-timesheet-admin-footer.vue
- pages/records.vue
Admin can un-approve a timesheet previously approved
https://github.com/FrontMen/fm-hours/issues/56
@unapprove event in weekly-timesheet-admin-footer
* Unapprove button with an approved timesheet in admin view
* @unapprove event triggers saving timesheet with status NEW
* bottom margin to in weekly-timesheet-admin-footer for better layout
1. As an admin, go to /timesheets and visit an approved timesheet
2. Hit the unapprove button (undo approval)
3. Check the timesheet is NEW in /timesheets and/or firestore
> Unapprove button for admin

- pages/records.vue
Wrapped timesheet inputs in a form, to allow correct mobile navigation
https://github.com/FrontMen/fm-hours/projects/1#card-62696041
records.vue rows timesheet rows, travel allowance rows and comment wrapped inside a form to allow for easy mobile navigation
1. Access / with mobile
2. Fill in value and hit next on keyboard
3. Check that next allows you to navigate all the way to comment
4. Other accessibility mobile navigation not included in this story
5. Visual changes not included
> Wrap timesheet inputs in a form for correct mobile navigation

- .eslintignore
- helpers/email.ts
- package.json
- pages/employees/_employee_id.vue
- pages/employees/index.vue
Display of employee name and email in the employee overview page
https://github.com/FrontMen/fm-hours/issues/125
* email field / name field
* basic email regex
* basic form validation for name and email
* fixed issue with boolean type on styling prop
* fixed the git-hooks to correctly lint (and only lint) the changed files on commit
* removed prettier on git-hook (for now)
* set typescript compiler type checking to only check ts/js files that are committed (during git-commit hook)
* eslint and prettier now _correctly_ use the `.eslintignore` instead of the `.gitignore`
* fix formatting in `_employee_id.vue`
* Open an employee in the employee overview
* you can now edit and view the name and email of an employee
* save changes
* refresh page to view (check firebase to validate save) …
> feat: add edit/display of name/email in the employee overview page

- components/app/top-bar.vue
Added feedback link in topbar. 
Visible on all pages, but sufficiently out of sight. 
Placed to the lefthand side not to compete with user name for space or be too distracting (increased size on text thus weight in that area), yet it stays clear and easy to find.
Simple external link, nothing fancy. 
https://github.com/FrontMen/fm-hours/issues/179
Go to app
Click on "feedback"
it opens a google form in a new tab
> Feature feedback link

- components/reports/month-navigation-buttons.vue
- pages/records.vue
Changed layout of month nav.
Previously, based on month name, the button for current would jump around. Now button in center, always visible, and with handy tooltip to clarify what it does.
Also added year since we can move through the months indefinitely.
closes https://github.com/FrontMen/fm-hours/issues/184
1. Go to /month or /reports 
2. Test month navigation
3. Note no weird button jumps as in the ticket
> fix: change layout of monthly nav to make it more predictable

- components/reports/reports-table.vue
- pages/reports.vue
adding "lazy" to a tab makes sure to mount and unmount inner components based on which tab is active.
This prevents retrieving all tables with querySelectorAll without needing ref or classes. 
closes https://github.com/FrontMen/fm-hours/issues/190
Added lazy propriety on b-tab in reports
1. Go to /reports
2.  Download csv on any of the tabs
3. The downloaded csv, with coresponding name based on tab, should only contain data visible in that tab
> fix: make sure csv only exports correct tables

- composables/useTimesheet.ts
- pages/records.vue
Resolves #199 
- `cancelAutoSave` function
N/A
- Auto-save logic now is in the `useTimesheet.ts`
- Cancel auto-save when navigating to other week
- Resume auto-save if cancel navigation
- fill in comments for current week
- before it saves, hit previous week
- when prompted, click ok to navigate away
- aut-save should be cancelled 
N/A
> fix(records): cancel saving when changing week

- components/records/comment-block.vue
- composables/useTimesheet.ts
- helpers/helpers.ts
- pages/records.vue
- store/timesheets/actions.ts
- store/timesheets/mutations.ts
- store/timesheets/state.ts
- types/timesheets.d.ts
Resolves #177 
- Comments now are a thread of messages
- Copying comments when clicking in "copy previous week"
- Previous message structure, as a single string, is still supported.
- New comments will be saved as an array of strings
- Go to any timesheet
- Add a new comment
- Add another comment
- All comments should be displayed as a sequence of commentary blocks
- Copy previous week shouldn't copy the comments
- All other behaviours should stay as before
> Feat: message history

- components/records/weekly-timesheet-row.vue
Resolves #221 
N/A
N/A
- The totals calculation now returns a `0` when there is no input.
- When editing a timesheet, delete an input value.
- The total row should show a `0` as value inputed.
N/A
> fix(records): show 0 instead of NaN

- components/records/weekly-timesheet-totals-row.vue
- pages/records.vue
- services/work-scheme-service.ts
- store/records/actions.ts
- store/records/mutations.ts
- store/records/state.ts
- types/records.d.ts
closes #220 
showing a notification when bridge API is down
replaces `-` with `0` in the totals row
removed validation when workscheme can't be fetched
- In Chrome block the request to `http://localhost:3000/api/v1` 
- Go to records, a notifications should be shown.
- `-` should be replaced with `0`
- Submitting hours shouldn't trigger validation
> feat: records add notification when workscheme can't be fetched

- pages/records/index.vue
Added data checks on the templates to ensure we only display ones with values.
https://github.com/FrontMen/fm-hours/issues/222
- variable to check value for travel kms
- variable to check employee standby hours
- used variables in v-if on the standby and travel allowance components
Check for isAdminView
> fix(timesheets): implement data checks for standby hours and travel kms

- pages/month.vue
Fixed rounding issue on monthly overview
https://github.com/FrontMen/fm-hours/issues/234
`toFixed` function
`toPrecision` function
Replaced `toPrecision` function with the more correct `toFixed` function
> fix: rounding error

- composables/useTimesheet.ts
Check for unsaved changes before doing a timesheet save
https://github.com/FrontMen/fm-hours/issues/225
Added check for unsaved changes before running save logic
Removed check around autosave code that was only being run during week changes
Unsaved data checks
- change data in the timesheet
- wait for autosave (5 seconds)
- change data in the timesheet again but then hit "Update" button
- wait to see if autosave triggers again (should not flash now - since autosave shouldn't trigger)
> fix: check unsaved changes before saving

- .eslintignore
- .prettierignore
- components/reports/reports-table.vue
@matthiasdeboer was having problems importing exported CSV files into excel. Decimal values like 275.75 were showing as 27575 for him. This happens because his system configuration expected decimal values to be separated by a comma, instead of a dot. To fix this I converted strings that contain a decimal value to use comma separator.
Export a CSV file containing decimal values from the report page and ask Matthias to try to import it into excel. (I did this already)
> fix: use european pattern for decimal numbers exported in the csv

- pages/records/index.vue
Removed admin specific checks that would hide the travel allowance/ standby hours for the employees
https://github.com/FrontMen/fm-hours/issues/253
some thought
admin specific checks
Allowed employees to log hours for standby and travel allowance kms
Employees can log hours for standby and travel allowance kms
> fix: remove admin specific checks

- pages/records/index.vue
Hide empty travel allowances and standby hours in admin view
https://github.com/FrontMen/fm-hours/issues/253
Checks for admin view determining whether there are values tracked in the travel allowances and standby hours respectively
old in line checks
added computed variable checks to hide empty tables
- in timesheets view, click a person's week who has travel/standby toggled on
- if there are no values tracked for travel/standby the tables should be hidden
- tables should be viewed only if they have values tracked.
- employees can track their hours/kms in the standard home page
> fix: hide empty standby and travel allowances in admin view

- composables/useTimesheet.ts
Improved save check to include the timesheet status
https://github.com/FrontMen/fm-hours/issues/262
Check for timesheet status
n/a
improved save check logic to include timesheet status which was preventing approval saves
timesheets can be approved again
> fix: add check for timesheet status in save

- pages/index.vue
We were referring `recordStatus` on `index.vue` without exposing it via `setup` method and this made impossible to update a timesheet
> fix: expose recordStatus via setup

- components/records/weekly-timesheet-footer.vue
- components/records/weekly-timesheet-row.vue
- pages/timesheets/_employee_id/_start_timestamp.vue
Removes autosave functionality on timesheets
Includes some refactors based on linting on touched components
https://github.com/FrontMen/fm-hours/issues/271
1. Got ot timesheet
2. add a project
3. set an hour value and blur
4. wait few seconds - no autosave
5. save - save functionality works as expected
6. write a comment and blur
7. autosave not fired after a few seconds
8. save works as intended
Update button changed to "Save"
> feat: remove timesheet autosave

- api/bridge/contracts/index.ts
- api/bridge/me.ts
- api/bridge/worklogs/[worklogId].ts
- api/bridge/worklogs/index.ts
- api/bridge/workscheme/[bridgeUid].ts
- components/employees/employee-form.vue
- lib/axios.ts
- lib/intracto.ts
In order to prevent the sending of POST, PUT, UPDATE and DELETE to the IO bridge PROD api during development, I instantiated an Axios client used in the `/api` layer, to which I added a request interceptor.
> chore: stop sending non-get api requests to bridge production from development

- store/reports/getters.test.ts
- store/reports/getters.ts
https://github.com/FrontMen/fm-hours/issues/805
No more rows with 0 standby hours in standby report
Navigate to Reports > stand-by
> feat: reports standby report

- components/records/weekly-timesheet.vue
https://github.com/FrontMen/fm-hours/issues/811
Setting an empty array as default value also affecting getWorkScheme API call, since it was undefined and the consequent helper functions were looking for an array.
Not sure how and when it happens that a workScheme can be empty (maybe missing info in Firebase?), but that's the problem I was experiencing myself.
> fix: set default empty array also after getWorkScheme API request

- components/records/weekly-timesheet-row.vue
- components/reports/date-reports.vue
New synced column on the worksheet table on the insights page is added to indicate whether it has been put into Bridge.
The icon that previously indicated that a worksheet has been put in Bridge, has been updated to `cloud-check` https://icons.getbootstrap.com/icons/cloud-check/
Visit the insights page. As admin you should see the new Synced column.
> feat: indicate the Bridge sync state in insights view

- components/employees/contract/contract-modal-content.vue
https://github.com/FrontMen/fm-hours/issues/825
Fixed the id used for building the billing contact link within the contract modal
> fix: contract modal billing contact link

- components/records/weekly-timesheet.vue
- layouts/default.vue
- store/auth/actions.ts
Before we were calling `router.push()` manually every time we dispatched a logout action every where this was done. I've put it within the action itself and removed the redundancy.
Try to log out across all possible scenarios.
> refactor/Call router.push once on logout

- services/employees-service.ts
Recently I made a change that we add the isAdmin prop to the employee in the frontend while it's 2 collections in firestore.
When a new employee logs in for the first time we retrieve a bridgeUid and we update the employee with this new ID.
This is the only time that a non-admin edits an employee.
Because we were always updating the admin list, without even checking if it changed, a non-admin would try to update the admin collection.
This results in a permission violation based on the firestore security rules.
> fix: only update admins if we need to

- components/app/top-bar.vue
- pages/admin/employees/index.vue
- pages/insights/index.vue
getMonth returns 0 for January which broke the redirects on 3 places.
> fix: redirecting to current month is broken

- services/teams-service.ts
fixes: #848
Sorting of teams when retrieving them for the team dropdown in Timesheet page.
N/A
Added sort to teams get / map.
Go to `/admin/timesheets` and check out the teams in dropdown are now alphabetically sort
<table>
<tr>
<td>OLD</td>
<td>NEW</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
> fix: teams not being sorted alphabetical
