FrontMen/fm-hours

components/app/user-header.vue, pages/records.vue, pages/timesheets/_user_id.vue, pages/users/_user_id.vue, pages/users/index.vue, services/users-service.ts, store/users/actions.ts, types/user.d.ts
Adds admin page on which you can select on which projects a user can write hours on.
resolves #19
=> Feat: user specific projects

components/records/navigation-buttons.vue, helpers/dates.ts, pages/index.vue
Changed the visual representation of the data navigation
=> chore: make button navigation inline

package.json, pages/employees/_employee_id.vue, yarn.lock
Solves #55 
- Vue Multi-select lib
N/a
- Now we select the customers for the employees using a search dropdown input instead of a switch.
- Add new projects to an employee
=> Feat: customer search input

pages/customers/_customer_id.vue, pages/customers/index.vue, services/customers-service.ts, store/customers/actions.ts, store/customers/mutations.ts
Solves #106 
- Edit customer page
N/A
- Delete button is now on the edit page
- Try to edit and/or delete a customer
=> Feat: edit customer

.gitignore, store/employee/actions.ts
=> feat: use Intracto authentication

helpers/helpers.ts, pages/employees/index.vue
Resolves #92 
- Employee name, status, and customers filter on employees page
N/A
- Employees page buttons are now anchor tags
- Go to the employees' page
- Add filters
- Check if the return is the expected one
=> Feat: filter employees

.firebaserc, .gitignore, components/app/top-bar.vue, layouts/default.vue, nuxt.config.ts, package.json, services/employees-service.ts, store/employee/actions.ts
Add the .env.dev to the dev script
some basic styling to make sure developers know if they are in dev or production "mode"
update the firebaserc to allow the dev env (not needed but prettier?)
update git ignore to ignore new env file
* run `yarn dev`
* check if everything works correctly
* check there are no regressions
=> feat: Setup the dev env and ignore the new dev file

pages/employees/index.vue
toLowerCase() when creating a user through the admin ui.
* create a user through the admin UI with capitalization in the user email.
* check the firestore to make sure the user email is all lowercase.
=> fix(employee): lower case emails when user is created

pages/timesheets/index.vue
=> feat: show 6 weeks before in timesheets overview

pages/records.vue, pages/timesheets/index.vue
=> fix: add null check for employee name

README.md, composables/useMonthlyKilometersReport.ts, pages/reports.vue
- Function renamed from `createKilomtersItems` to `createKilometersItems` 
- README updated
No test required
=> Fixe small typo and improve README

assets/scss/_variables.scss, pages/timesheets/index.vue
#145
Added missing colors for NEW and DENIED. Also when hovering over it will show a tooltip.
EMPTY = gray
APPROVED = turquoise
NEW = green
DENIED = red
Pending = orange
=> fix: add missing status colors and title on hover

components/timesheets/weekly-pending-timesheet.vue, helpers/dates.ts, helpers/timesheet.ts, pages/timesheets/index.vue, types/timesheets.d.ts
=> feat: add weeknumbers to timesheets

components/records/weekly-timesheet-row.vue
https://github.com/FrontMen/fm-hours/issues/168
New Tooltip confirmation dialog before deleting the project from timesheet.
Add multiple projects and try to delete them
https://user-images.githubusercontent.com/7356299/125807874-a8a888b4-2b36-42b7-a75f-e409997c995b.mov
=> feat: add tooltip validation before deleting project

components/records/weekly-timesheet-row.vue, helpers/helpers.ts, pages/records.vue
https://github.com/FrontMen/fm-hours/issues/172
Now with debounce of 5 seconds, any changes are autosaved in timesheet edits.
Start editing hours, kms and comment messages. It should trigger an autosave after 5 seconds
=> feat: implement save on blur with debounce 5 seconds

services/employees-service.ts
N/A
N/A
- The code block where the employee is searched by `employeeId`
N/A
- Run `yarn generate`
- Run `yarn start`
- Try to login
- The app should complete the login flow as expected
N/A
=> fix(employee): remove query by id

components/records/weekly-timesheet-totals-row.vue
https://github.com/FrontMen/fm-hours/issues/196
Added new "theoratical hours" information to `weekly-timesheet-row`
See if there theoratical hours are present 🤷‍♂️
=> feat: show theoratical hours in the total row

pages/customers/_customer_id.vue
Prompt for confirmation of changing isBillable state of a customer
closes https://github.com/FrontMen/fm-hours/projects/1#card-65717046
1. Go to /customers
2. Go to manage customer
3. Toggle billable
4. hit update
5. note a prompt
=> feat: prompt when changing isBillable flag of a project

helpers/api.ts, nuxt.config.ts, plugins/services.ts, services/auth-service.ts, services/work-scheme-service.ts, store/employee/actions.ts
https://github.com/FrontMen/fm-hours/issues/205
* helper for the API proxy/url selector
* new parameters to auth api calls for the dev  context 
* the way the API url is created for the auth URLS in api calls
* test on the deployed instance of the app vs localhost. URLs should not be proxied in the deployed instance.
=> fix: setup correct URL for prod/dev proxies

components/records/navigation-buttons.vue, components/reports/month-navigation-buttons.vue, pages/records/index.vue
changed request leave notification into a button
changed the layout of the buttons
#228 #229
go to records view
=> feat: records refactor navigation buttons and Request Leave

helpers/api.ts, nuxt.config.ts, plugins/services.ts, services/auth-service.ts, services/work-scheme-service.ts, store/employee/actions.ts
=> fix: use ssr proxy

nuxt.config.ts, vercel.json
Added SSR to the config for the vertel build
=> build: change to ssr

composables/useMonthlyKilometersReport.ts, composables/useMonthlyProjectsReport.ts, composables/useMonthlyStandbyReport.ts, composables/useMonthlyTotalsReport.ts, store/reports/mutations.ts, types/reports.d.ts
https://github.com/FrontMen/fm-hours/issues/244
added a team column to all 4 reports on the reports page
etc...
=> feat: team column in reports

components/records/navigation-buttons.vue
When editing my own timesheet:
When editing/viewing someone's else timesheet:
=> feat: hide request leave button when viewing/editing others' timesheets

components/timesheets/weekly-timesheet-admin-footer.vue, composables/useTimesheet.ts, pages/records/index.vue
Change button "Approve" to "Approve and go to next",
So, instead of just approving the timesheet, it also goes to the next one.
Approve a timesheet.
=> feat: replace "approve" to "approve and go to next"

pages/index.vue
[257](https://github.com/FrontMen/fm-hours/issues/257)
A hacky way to log in to production, as discussed in the standup.
=> fix: production login (temporary hack)

components/records/navigation-buttons.vue, composables/useTimesheet.ts, pages/index.vue, pages/timesheets/_employee_id/_start_timestamp.vue, services/timesheets-service.ts, store/auth/actions.ts
* deprecated useTimesheet
* split admin and user functionality correctly between pages (`index.vue` / `_start_timestamp.vue`)
* log in as user
* view/add/edit your timesheet
* log in as admin
* selected timesheets from burger menu
* view any timesheet / approve / reject timesheet
=> Initial Feat/timesheet refactor

.github/workflows/app.yml
This PR only introduces Github Actions runners to ensure quality
=> [CI] Add app CI runners

pages/month.vue
=> fix: endDate being ref

components/app/top-bar.vue, nuxt.config.ts, pages/index.vue, pages/timesheets/_employee_id/_start_timestamp.vue
set theme orange as progress bar, it used to be black over black
fix width for hamburger menu
fix link for email reminders - timestamp is string and results in invalid Date, breaking the return of records
=> Small fixes 

pages/timesheets/_employee_id/_start_timestamp.vue
https://github.com/FrontMen/fm-hours/issues/289
https://github.com/FrontMen/fm-hours/issues/288
Approve/reject/remind/update functionality
User functionality: 
* update timesheets
* add/remove client/project
approve/deny/send reminder/add comments on the admin page. Functionality should work as expected.
=> add admin functionality, remove user functionality from timesheet page

components/records/controls.vue, pages/timesheets/_employee_id/_start_timestamp.vue, types/timesheets.d.ts
controls components
comments from the footer in the timeshet
=> chore: move comments to dropdown

components/records/navigation-buttons.vue, nuxt.config.ts
=> feat: get back the keyboard navigation for switching weeks

components/records/weekly-timesheet.vue
=> fix: prevent duplicates

nuxt.config.ts, package.json, yarn.lock
=> fix: be able to run vercel locally

components/records/weekly-timesheet-container.vue, components/records/weekly-timesheet-row-leave.vue, components/records/weekly-timesheet.vue, helpers/timesheet.ts, store/auth/actions.ts, types/records.d.ts, types/timesheets.d.ts
=> Workscheme improvements

store/auth/actions.ts, store/index.ts
https://github.com/FrontMen/fm-hours/issues/454
=> fix(): stateful routes

.eslintrc.js, .prettierrc.js, README.md, api/bridge/contracts/[contractId].ts, api/bridge/contracts/index.ts, api/bridge/me.ts, components/records/weekly-timesheet-container.vue, functions/.eslintrc.js, functions/src/index.ts, functions/src/sendMail.ts, functions/tsconfig.dev.json, functions/tsconfig.json, helpers/hmac-generator.ts, nuxt.config.ts, package.json, plugins/services.ts, plugins/thirdPartyComponents.ts, services/contracts-service.ts, yarn.lock
https://github.com/FrontMen/fm-hours/issues/268
Added prettier, contracts API (which is not used in actual code yet)
=> feat(): added contracts api

components/employees/employee-form.vue, lang/en.js, lang/nl.js, pages/admin/employees/_id.vue, pages/employees/add.vue
Fixed bug in saving an employee causing the app to crash.
fixes https://github.com/FrontMen/fm-hours/issues/459
=> fix(): saving changes to employee

api/bridge/auth.ts
=> fix: logout user when bridge auth gives 401

services/employees-service.ts
=> fix: temporary check for iodigital.com mail addresses

store/reports/actions.ts, store/reports/mutations.ts
=> fix: show leave in reports

components/records/weekly-timesheet-messages.vue, components/records/weekly-timesheet.vue
#412 
- Passed the employee's name to the addMessage method
Try to comment on your hours sheet as an admin and as a user, you should see the name of the admin as well as the name of the employee.
=> feat(add-name-to-comments): added name prop

lang/en.js, lang/nl.js, pages/admin/timesheets.vue
#569 
- Added input for selecting a team
- Filter for searching based on a team
- Select a team, the list should change
- Try to select a team and check the "hide done" checkbox
=> feat(filter-timesheets-based-on-team): added select team input

.github/workflows/app.yml
=> fix: remove installing lerna

components/records/weekly-timesheet.vue
=> fix: when adding worklog items, delete existing ones

components/app/top-bar.vue
=> feat: remove feedback button

components/employees/contract/contract-modal-content.vue, components/employees/contract/external-link.vue, components/employees/project-selector.vue
https://github.com/FrontMen/fm-hours/issues/806
Removed the JSON payload dump from contract details modal
Navigate Admin > Employees > Click on an employee
=> feat: contract modal improvements

components/records/weekly-timesheet-messages.vue
=> fix: disable comments dropdown

components/reports/kilometers-report.vue, components/reports/not-billable-report.vue, components/reports/not-synced.vue, components/reports/reports-table.vue, components/reports/stand-by-report.vue, components/reports/totals-report.vue
=> fix: refactor table export
